### ISSUE TITLE
errors being eaten with tests

### ISSUE THREAD

**Issue by ErichBSchulz** [civicrm/api4#46]
so this had me stumped:

```
.PHP Fatal error:  Uncaught PEAR_Exception: DB Error: unknown error in unknown on line unknown
 DB_Error: DB Error: unknown error in unknown on line unknown
#0 [internal function]: CRM_Core_Error::exceptionHandler(Object(DB_Error))
#1 /opt/buildkit/build/dmaster/sites/all/modules/civicrm/packages/PEAR.php(921): call_user_func(Array, Object(DB_Error))
#2 /opt/buildkit/build/dmaster/sites/all/modules/civicrm/packages/DB.php(985): PEAR_Error->__construct('DB Error: unkno...', -1, 16, Array, 'ROLLBACK TO SAV...')
#3 /opt/buildkit/build/dmaster/sites/all/modules/civicrm/packages/PEAR.php(575): DB_Error->__construct(-1, 16, Array, 'ROLLBACK TO SAV...')
#4 [internal function]: PEAR->_raiseError(Object(DB_mysqli), NULL, -1, NULL, NULL, 'ROLLBACK TO SAV...', 'DB_Error', true)
#5 /opt/buildkit/build/dmaster/sites/all/modules/civicrm/packages/PEAR.php(224): call_user_func_array(Array, Array)
#6 /opt/buildkit/build/dmaster/sites/all/modules/civicrm/packages/DB/common.php(1905): PEAR->__call('raiseError', Array)
#7 /opt/buildkit/build/dmast in /opt/buildkit/build/dmaster/sites/all/modules/civicrm/CRM/Core/Error.php on line 938
```

the error log contained:

```
Mar 01 07:32:24  [info] $backTrace = #0 /opt/buildkit/build/dmaster/sites/all/modules/civicrm/CRM/Core/Error.php(937): CRM_Core_Error::backtrace("backTrace", TRUE)
#1 [internal function](): CRM_Core_Error::exceptionHandler(Object(DB_Error))
#2 /opt/buildkit/build/dmaster/sites/all/modules/civicrm/packages/PEAR.php(921): call_user_func((Array:2), Object(DB_Error))
#3 /opt/buildkit/build/dmaster/sites/all/modules/civicrm/packages/DB.php(985): PEAR_Error->__construct("DB Error: unknown error", -1, 16, (Array:2), "ROLLBACK TO SAVEPOINT civi_2 [nativecode=1305 ** SAVEPOINT civi_2 does not ex...")
#4 /opt/buildkit/build/dmaster/sites/all/modules/civicrm/packages/PEAR.php(575): DB_Error->__construct(-1, 16, (Array:2), "ROLLBACK TO SAVEPOINT civi_2 [nativecode=1305 ** SAVEPOINT civi_2 does not ex...")
#5 [internal function](): PEAR->_raiseError(Object(DB_mysqli), NULL, -1, NULL, NULL, "ROLLBACK TO SAVEPOINT civi_2 [nativecode=1305 ** SAVEPOINT civi_2 does not ex...", "DB_Error", TRUE)
#6 /opt/buildkit/build/dmaster/sites/all/modules/civicrm/packages/PEAR.php(224): call_user_func_array((Array:2), (Array:8))
#7 /opt/buildkit/build/dmaster/sites/all/modules/civicrm/packages/DB/common.php(1905): PEAR->__call("raiseError", (Array:7))
#8 /opt/buildkit/build/dmaster/sites/all/modules/civicrm/packages/DB/common.php(1905): PEAR->raiseError(NULL, -1, NULL, NULL, "ROLLBACK TO SAVEPOINT civi_2 [nativecode=1305 ** SAVEPOINT civi_2 does not ex...", "DB_Error", TRUE)
#9 /opt/buildkit/build/dmaster/sites/all/modules/civicrm/packages/DB/mysqli.php(933): DB_common->raiseError(-1, NULL, NULL, NULL, "1305 ** SAVEPOINT civi_2 does not exist")
#10 /opt/buildkit/build/dmaster/sites/all/modules/civicrm/packages/DB/mysqli.php(403): DB_mysqli->mysqliRaiseError()
#11 /opt/buildkit/build/dmaster/sites/all/modules/civicrm/packages/DB/common.php(1216): DB_mysqli->simpleQuery("ROLLBACK TO SAVEPOINT civi_2")
#12 /opt/buildkit/build/dmaster/sites/all/modules/civicrm/packages/DB/DataObject.php(2438): DB_common->query("ROLLBACK TO SAVEPOINT civi_2")
#13 /opt/buildkit/build/dmaster/sites/all/modules/civicrm/packages/DB/DataObject.php(1627): DB_DataObject->_query("ROLLBACK TO SAVEPOINT civi_2")
#14 /opt/buildkit/build/dmaster/sites/all/modules/civicrm/CRM/Core/DAO.php(354): DB_DataObject->query("ROLLBACK TO SAVEPOINT civi_2")
#15 /opt/buildkit/build/dmaster/sites/all/modules/civicrm/Civi/Core/Transaction/Frame.php(163): CRM_Core_DAO->query("ROLLBACK TO SAVEPOINT civi_2")
#16 /opt/buildkit/build/dmaster/sites/all/modules/civicrm/Civi/Core/Transaction/Manager.php(117): Civi\Core\Transaction\Frame->finish()
#17 /opt/buildkit/build/dmaster/sites/all/modules/civicrm/CRM/Core/Transaction.php(142): Civi\Core\Transaction\Manager->dec()
#18 /opt/buildkit/build/dmaster/sites/all/modules/civicrm/Civi/Test/CiviTestListener.php(72): CRM_Core_Transaction->commit()
#19 phar:///opt/buildkit/bin/phpunit4/phpunit/Framework/TestResult.php(340): Civi\Test\CiviTestListener->endTest(Object(Civi\API\V4\ParticipantTest), 0.13832211494446)
#20 phar:///opt/buildkit/bin/phpunit4/phpunit/Framework/TestResult.php(733): PHPUnit_Framework_TestResult->endTest(Object(Civi\API\V4\ParticipantTest), 0.13832211494446)
#21 phar:///opt/buildkit/bin/phpunit4/phpunit/Framework/TestCase.php(724): PHPUnit_Framework_TestResult->run(Object(Civi\API\V4\ParticipantTest))
#22 phar:///opt/buildkit/bin/phpunit4/phpunit/Framework/TestSuite.php(747): PHPUnit_Framework_TestCase->run(Object(PHPUnit_Framework_TestResult))
#23 phar:///opt/buildkit/bin/phpunit4/phpunit/Framework/TestSuite.php(747): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
#24 phar:///opt/buildkit/bin/phpunit4/phpunit/TextUI/TestRunner.php(440): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
#25 phar:///opt/buildkit/bin/phpunit4/phpunit/TextUI/Command.php(149): PHPUnit_TextUI_TestRunner->doRun(Object(PHPUnit_Framework_TestSuite), (Array:5))
#26 phar:///opt/buildkit/bin/phpunit4/phpunit/TextUI/Command.php(100): PHPUnit_TextUI_Command->run((Array:1), TRUE)
#27 /opt/buildkit/bin/phpunit4(545): PHPUnit_TextUI_Command::main()
#28 {main}
```

after a bit of snooping I found i could fix this by commenting out a couple of lines in `civicrm/Civi/Test/CiviTestListener.php`:

```php
 70   public function endTest(\PHPUnit_Framework_Test $test, $time) {
 71     if ($test instanceof TransactionalInterface) {
 72 //      $this->tx->rollback()->commit();
 73 //      $this->tx = NULL;
 74     }
```

not sure about next steps...

**Comment by ErichBSchulz** [comment]
@colemanw @totten any pointers? not sure if it is way I've set up my test classes or if this is a core issue

**Comment by mickadoo** [comment]
@ErichBSchulz I have seen this error before, I think it was because I was pointing to the wrong database, but I'm not sure. Is it still an issue for you?

**Comment by ErichBSchulz** [comment]
nope - I was stumped - I can't remember the outcome i think it is possible I just left those 2 lines commented out - if no-one can reproduce then I suggest closing
